#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Set TOTAL_STAGES to match the stages written below.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# The manager's own checkout, resolved the way src/adapters/manager-home.ts
# resolves it: from this file, and overridable for a second checkout.
MANAGER_HOME="${SIDE_PROJECTS_MANAGER_HOME:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
BUDGET_FILE="$MANAGER_HOME/budget.json"
STATE_FILE="$MANAGER_HOME/state.json"

# DEFAULT_BUDGET in src/ports/budget.ts. Kept honest by stage 7, which reads
# the written document back through the manager's own parser.
DEFAULT_FIVE_HOUR=5000000
DEFAULT_WEEKLY=50000000
DEFAULT_RESERVE=0.5
DEFAULT_CEILING=5

# What this wizard produces is budget.json, not an env file or a CI secret,
# so write_env/set_secret go unused and the closing summary is written by hand.

# _commas N groups a long token count for reading: 5000000 -> 5,000,000.
_commas() { printf '%s' "$1" | sed -e ':a' -e 's/\B[0-9]\{3\}\>/,&/;ta'; }

# _valid KIND VALUE: whether VALUE is usable, by the same rules the manager
# parses the document with -- isTokenCount/isReserveFraction/isUsd in
# src/ports, plus the "an allowance is never 0" rule in document-store.ts.
_valid() {
  node --input-type=module -e '
const [kind, raw] = process.argv.slice(1);
const value = Number(raw);
const rule = {
  allowance: (v) => Number.isSafeInteger(v) && v > 0,
  fraction: (v) => Number.isFinite(v) && v >= 0 && v < 1,
  usd: (v) => Number.isFinite(v) && v > 0,
}[kind];
process.exit(raw.trim() !== "" && rule(value) ? 0 : 1);
  ' "$1" "$2" 2>/dev/null
}

# _expected KIND: the rule a rejected answer broke, in the document's terms.
_expected() {
  case "$1" in
    allowance) printf 'a whole number of tokens above 0 (an allowance of nothing would authorise a run every morning, not stop them)' ;;
    fraction)  printf 'at least 0 and less than 1 (a reserve of 1 holds back the whole week, so no run could ever start)' ;;
    usd)       printf 'a dollar amount above 0' ;;
  esac
}

# _budget_field NAME: the current value in budget.json, or nothing if the
# document is absent, unreadable, or does not carry that field as a number.
_budget_field() {
  node --input-type=module -e '
const fs = await import("node:fs");
const [file, field] = process.argv.slice(1);
let document;
try { document = JSON.parse(fs.readFileSync(file, "utf8")); } catch { process.exit(0); }
const value = document?.[field];
if (typeof value === "number" && Number.isFinite(value)) process.stdout.write(String(value));
  ' "$BUDGET_FILE" "$1" 2>/dev/null
}

# _seed FIELD DEFAULT: what a stage starts from -- what the document already
# says, falling back to DEFAULT_BUDGET. This is what makes a re-run a review
# of the budget in force rather than a retyping of it.
_seed() {
  local current
  current=$(_budget_field "$1")
  printf '%s' "${current:-$2}"
}

# ask_value KEY "Prompt" KIND DEFAULT: asks until the answer is one the
# manager would accept. Blank keeps DEFAULT; commas and underscores in a long
# number are accepted, since a nine-digit allowance is unreadable without them.
ask_value() {
  local key="$1" prompt="$2" kind="$3" fallback="$4" input
  while true; do
    ask "$key" "$prompt [$(_commas "$fallback")]:"
    input="${!key}"
    input="${input//,/}"
    input="${input//_/}"
    input="${input// /}"
    [[ -z "$input" ]] && input="$fallback"
    if _valid "$kind" "$input"; then
      printf -v "$key" '%s' "$input"
      printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$(_commas "$input")"
      return 0
    fi
    warn "expected $(_expected "$kind") — got '$input'."
  done
}

# Every answer is checked against the predicates in src/ports, and the
# finished document is read back through the manager's own parser, so this
# wizard is worth nothing without the node the manager itself runs on.
if ! command -v node >/dev/null 2>&1; then
  printf 'This wizard needs node (>= 22.18, the version package.json asks for):\n' >&2
  printf 'it checks every answer against the same predicates src/ports uses, and\n' >&2
  printf "reads the finished budget back through the manager's own parser.\n" >&2
  exit 1
fi

banner "Side Projects Manager: the budget"

# ── Stage 1: what the mornings have actually been spending ────────────────
stage "Calibrate against real spend"
say "budget.json is yours: four numbers the morning loop asks before it starts"
say "anything. They are declarations rather than measurements — the provider"
say "reports what you have consumed and never what you have left — so the one"
say "thing worth setting them against is what your runs have actually cost."
printf '\n'
say "Writing to: $BUDGET_FILE"

if [[ -f "$BUDGET_FILE" ]]; then
  note "a budget document is already here; each answer below starts from it."
else
  note "no budget document yet — the loop has been running on DEFAULT_BUDGET."
fi
printf '\n'

if spend=$(node --input-type=module -e '
const fs = await import("node:fs");
const [file] = process.argv.slice(1);
let document;
try { document = JSON.parse(fs.readFileSync(file, "utf8")); } catch { process.exit(3); }
const runs = Object.entries(document?.projects ?? {}).flatMap(
  ([repo, project]) => (project?.runs ?? []).map((run) => ({ repo, ...run })),
);
if (runs.length === 0) process.exit(3);
const now = Date.now();
const within = (ms) => runs.filter((run) => now - Date.parse(run.at) <= ms);
const total = (rs) => rs.reduce((sum, run) => sum + (run.tokensUsed ?? 0), 0);
const fmt = (n) => n.toLocaleString("en-US");
const week = within(7 * 24 * 3600 * 1000);
const block = within(5 * 3600 * 1000);
const largest = runs.reduce((a, b) => ((b.tokensUsed ?? 0) > (a.tokensUsed ?? 0) ? b : a));
console.log(`${runs.length} run(s) recorded, ${fmt(total(runs))} tokens all told.`);
console.log(`Last 5 hours: ${fmt(total(block))} tokens over ${block.length} run(s).`);
console.log(`Last 7 days:  ${fmt(total(week))} tokens over ${week.length} run(s).`);
console.log(`Largest single run: ${fmt(largest.tokensUsed ?? 0)} tokens (${largest.repo}).`);
' "$STATE_FILE" 2>/dev/null); then
  say "What state.json records:"
  while IFS= read -r line; do note "  $line"; done <<<"$spend"
else
  note "state.json records no runs yet, so there is nothing to calibrate"
  note "against. Start cautious: the defaults below hold half the week back."
fi
printf '\n'
note "Those figures are the mornings' own spend only. Your Claude chat and your"
note "other machines stay invisible to the gate — the reserve is what absorbs"
note "them, which is why it is worth setting generously."
pause "Ready to set the four numbers?"

# ── Stage 2: the 5-hour window ────────────────────────────────────────────
stage "fiveHourAllowance"
say "Tokens you assume the 5-hour window holds."
printf '\n'
note "The gate refuses to start a run once the window has consumed more than"
note "this. The 5-hour window has no reserve of its own — the reserve is a"
note "share of the week — so it is measured against this figure whole: a spent"
note "block is a wall to wait out, not a supply to ration."
printf '\n'
ask_value FIVE_HOUR_ALLOWANCE "Tokens per 5-hour window" allowance \
  "$(_seed fiveHourAllowance "$DEFAULT_FIVE_HOUR")"
pause

# ── Stage 3: the weekly window ────────────────────────────────────────────
stage "weeklyAllowance"
say "Tokens you assume the weekly window holds."
printf '\n'
note "This is the window the reserve is taken out of, in the next stage. Being"
note "wrong here is safe in one direction only — too high spends a reserve you"
note "thought you had — so state it low and raise it as state.json fills in."
printf '\n'
ask_value WEEKLY_ALLOWANCE "Tokens per week" allowance \
  "$(_seed weeklyAllowance "$DEFAULT_WEEKLY")"
if (( WEEKLY_ALLOWANCE < FIVE_HOUR_ALLOWANCE )); then
  printf '\n'
  warn "the week ($(_commas "$WEEKLY_ALLOWANCE")) is smaller than one 5-hour block ($(_commas "$FIVE_HOUR_ALLOWANCE"))."
  note "Not rejected — the manager accepts it — but the weekly gate would then"
  note "refuse long before a single block ever filled up."
fi
pause

# ── Stage 4: the reserve held back for the developer ──────────────────────
stage "reserveFraction"
say "The share of the weekly allowance held back for you."
printf '\n'
note "At 0.5 the mornings may spend half the week, and the gate refuses once"
note "more than half is gone. This is the number the whole design exists for:"
note "the mechanical half of the work can never starve the expensive half."
note "0 holds nothing back, which is a choice you are allowed to make. 1 would"
note "hold the whole week back so no run could ever start — a typo rather than"
note "a setting, and refused here."
printf '\n'
ask_value RESERVE_FRACTION "Reserve fraction, 0 to just under 1" fraction \
  "$(_seed reserveFraction "$DEFAULT_RESERVE")"
node --input-type=module -e '
const [weekly, reserve] = process.argv.slice(1).map(Number);
const fmt = (n) => Math.round(n).toLocaleString("en-US");
console.log(`  the mornings may spend ${fmt(weekly * (1 - reserve))} tokens a week;`);
console.log(`  ${fmt(weekly * reserve)} stays yours.`);
' "$WEEKLY_ALLOWANCE" "$RESERVE_FRACTION"
pause

# ── Stage 5: the ceiling inside a single run ──────────────────────────────
stage "spendCeiling"
say "The most a single run may spend, in US dollars."
printf '\n'
note "Nothing is billed — runs go on your subscription. It is dollars because"
note "the agent CLI's --max-budget-usd flag is: the CLI prices the run's own"
note "token usage at API rates and stops the run when that priced total crosses"
note "the figure. So it is a token ceiling stated in the CLI's units."
printf '\n'
note "The gate decides whether a run starts; this bounds how far a started run"
note "can go. The gate does not subtract the run it is about to authorise, so a"
note "run started at the boundary spends this out of the reserve — the ceiling"
note "is the size of that accepted overshoot."
printf '\n'
ask_value SPEND_CEILING "Dollars per run" usd \
  "$(_seed spendCeiling "$DEFAULT_CEILING")"
pause

# ── Stage 6: review, then write the document ──────────────────────────────
stage "Review and write budget.json"
say "This is the document that will be written to $BUDGET_FILE:"
printf '\n'
BUDGET_JSON=$(node --input-type=module -e '
const fs = await import("node:fs");
const path = await import("node:path");
const url = await import("node:url");
const [home, file, ...numbers] = process.argv.slice(1);
const [fiveHour, weekly, reserve, ceiling] = numbers.map(Number);
const ports = url.pathToFileURL(path.join(home, "src", "ports", "index.ts")).href;
const { isIterationLimit, isReserveFraction, isTokenCount, SIZES } = await import(ports);

// Fields carried across rather than asked about. This wizard replaces the
// document wholesale, and each of these is set by hand outside it, so a
// re-run that dropped one would quietly undo it: an observed reset put back
// the stand-downs it was written to stop, a concurrency limit put the
// mornings back to one at a time. Only a usable value is carried, since an
// unusable one would make the document fail to read back; dropping it falls
// back to the default, and the developer is told, since the manager would
// have refused that document rather than fall back.
const carried = {
  maxConcurrentIterations: (v) => typeof v === "number" && isIterationLimit(v),
  fiveHourReserveFraction: (v) => typeof v === "number" && isReserveFraction(v),
  sizes: (v) =>
    v !== null && typeof v === "object" && !Array.isArray(v) &&
    Object.entries(v).every(
      ([size, tokens]) => SIZES.includes(size) && typeof tokens === "number" && isTokenCount(tokens),
    ),
  unsizedCountsAs: (v) => typeof v === "string" && SIZES.includes(v),
  observedResetAt: (v) => typeof v === "string",
};
let existing;
try {
  existing = JSON.parse(fs.readFileSync(file, "utf8"));
} catch { /* no document yet, or one that will not parse: nothing to carry */ }

const kept = {};
for (const [field, usable] of Object.entries(carried)) {
  const value = existing?.[field];
  if (value === undefined) continue;
  if (usable(value)) {
    kept[field] = value;
  } else {
    process.stderr.write(`dropping "${field}": ${JSON.stringify(value)} is not a value the manager accepts, so the default applies\n`);
  }
}

process.stdout.write(JSON.stringify({
  fiveHourAllowance: fiveHour,
  weeklyAllowance: weekly,
  reserveFraction: reserve,
  spendCeiling: ceiling,
  ...kept,
}, undefined, 2));
' "$MANAGER_HOME" "$BUDGET_FILE" "$FIVE_HOUR_ALLOWANCE" "$WEEKLY_ALLOWANCE" "$RESERVE_FRACTION" "$SPEND_CEILING")
while IFS= read -r line; do printf '  %s%s%s\n' "$BOLD" "$line" "$RESET"; done <<<"$BUDGET_JSON"
printf '\n'
if [[ -f "$BUDGET_FILE" ]]; then
  warn "this replaces the budget document already at that path."
fi
note "The four fields asked about are stated outright, so reading the document"
note "back never depends on remembering what DEFAULT_BUDGET holds."
printf '\n'

if confirm "Write it?"; then
  # Written beside the document and renamed over it, the way the manager
  # writes its own: a write interrupted part way leaves the previous budget
  # intact rather than half a file the next morning cannot parse.
  printf '%s\n' "$BUDGET_JSON" >"$BUDGET_FILE.pending"
  mv "$BUDGET_FILE.pending" "$BUDGET_FILE"
  printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$BUDGET_FILE"
else
  SKIPPED+=("budget.json — nothing was written; re-run this wizard to set it")
  warn "not written. The loop goes on under the budget already in force."
fi
pause

# ── Stage 7: prove the loop will accept what was written ──────────────────
stage "Verify"
say "Reading the document back through the manager's own parser, so a"
say "misspelled field surfaces now rather than on a morning."
printf '\n'

if [[ ! -f "$BUDGET_FILE" ]]; then
  note "no document to verify — nothing was written."
elif parsed=$(node --input-type=module -e '
const path = await import("node:path");
const url = await import("node:url");
const [home] = process.argv.slice(1);
const store = url.pathToFileURL(path.join(home, "src", "adapters", "document-store.ts")).href;
try {
  const { documentStore } = await import(store);
  const budget = await documentStore(home).loadBudget();
  for (const [field, value] of Object.entries(budget)) {
    const shown = typeof value === "number" ? value.toLocaleString("en-US")
      : value instanceof Date ? value.toISOString()
      : typeof value === "object" ? JSON.stringify(value)
      : value;
    console.log(`${field}: ${shown}`);
  }
} catch (error) {
  // The parser message names the file and the setting, which is the whole of
  // what the developer has to act on; the stack behind it is this wizard.
  console.log(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
' "$MANAGER_HOME" 2>&1); then
  say "The loop reads this budget:"
  while IFS= read -r line; do printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$line"; done <<<"$parsed"
  printf '\n'
  note "A field that is present but unusable, or not one of the nine, fails the"
  note "invocation rather than falling back — which is what just passed."
else
  warn "the manager cannot read the budget document at that path:"
  while IFS= read -r line; do note "  $line"; done <<<"$parsed"
  SKIPPED+=("budget.json is at $BUDGET_FILE but the manager rejected it — fix it by hand before the next morning")
fi
printf '\n'
note "From here, state.json accumulates what the mornings actually cost. Re-run"
note "this wizard when those figures say the allowances were guesses worth"
note "revising: it starts from the budget in force, so nothing is retyped."

finish
