#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$HOME/.side-projects-manager.env"

RC_ENV_BEGIN="# >>> side-projects-manager: env >>>"
RC_ENV_END="# <<< side-projects-manager: env <<<"

# _install_rc_env RC_FILE: idempotently makes an interactive shell source
# ENV_FILE on startup. No-op if the rc file doesn't exist or already has it.
_install_rc_env() {
  local rc="$1"
  [[ -f "$rc" ]] || return 0
  if grep -qF "$RC_ENV_BEGIN" "$rc"; then
    note "$rc: env sourcing already installed."
    return 0
  fi
  printf '\n%s\n[ -f "%s" ] && set -a && . "%s" && set +a\n%s\n' \
    "$RC_ENV_BEGIN" "$ENV_FILE" "$ENV_FILE" "$RC_ENV_END" >>"$rc"
  printf '  %s✓%s %s: env sourcing installed.\n' "$GREEN" "$RESET" "$rc"
}

# _crontab_upsert_var NAME VALUE: sets NAME=VALUE as a crontab-level
# environment line (applies to every job below it), replacing any existing
# line for NAME. Cron reads neither .bashrc nor .zshrc, so this is the only
# way the schedule sees these credentials.
_crontab_upsert_var() {
  local name="$1" value="$2" existing
  existing="$(crontab -l 2>/dev/null || true)"
  { printf '%s=%s\n' "$name" "$value"
    printf '%s\n' "$existing" | grep -vE "^${name}=" | grep -v '^$' || true
  } | crontab -
}

banner "Side Projects Manager: setup"

# ── Stage 1: the Claude subscription token the sandbox authenticates with ──
stage "Claude subscription token"
say "The sandbox authenticates on your Claude subscription, never an API key."
existing_claude_token="$(_existing CLAUDE_CODE_OAUTH_TOKEN || true)"
if [[ -n "$existing_claude_token" ]]; then
  note "already saved in $ENV_FILE (ends …${existing_claude_token: -6})."
  if confirm "Regenerate it with 'claude setup-token'?"; then
    claude setup-token || warn "it exited non-zero — paste a token below, or leave blank to keep the saved one."
    ask_secret CLAUDE_CODE_OAUTH_TOKEN "Paste the new token it printed (blank keeps the saved one):"
  else
    CLAUDE_CODE_OAUTH_TOKEN="$existing_claude_token"
    note "keeping the saved token."
  fi
else
  say "This runs 'claude setup-token': it opens your browser for an OAuth"
  say "approval, then prints a long-lived token in this terminal."
  if confirm "Run 'claude setup-token' now?"; then
    claude setup-token || warn "it exited non-zero — paste a token below if you already have one, or skip."
  else
    note "skipped running it — run 'claude setup-token' yourself, then come back and paste the token."
  fi
  ask_secret CLAUDE_CODE_OAUTH_TOKEN "Paste the token it printed (blank to skip):"
fi
if [[ -n "$CLAUDE_CODE_OAUTH_TOKEN" ]]; then
  write_env CLAUDE_CODE_OAUTH_TOKEN "$CLAUDE_CODE_OAUTH_TOKEN"
else
  SKIPPED+=("CLAUDE_CODE_OAUTH_TOKEN — run 'claude setup-token' and add it to $ENV_FILE by hand; without it every run fails with 'Not logged in'")
fi

# ── Stage 2: the two GitHub tokens — one pushes, one is read-only ─────────
stage "GitHub tokens"
say "Two tokens: GH_TOKEN is what the agent pushes branches and opens PRs"
say "with. GH_REVIEW_TOKEN is what a review run gets instead — scoped so it"
say "can read issues/PRs but never push or merge, even from a throwaway clone."

GH_TOKEN_AUTO=""
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  GH_TOKEN_AUTO="$(gh auth token 2>/dev/null || true)"
fi
if [[ -n "$GH_TOKEN_AUTO" ]]; then
  note "found an active gh CLI login; reusing its token for GH_TOKEN."
  GH_TOKEN="$GH_TOKEN_AUTO"
else
  warn "gh isn't authenticated. Run 'gh auth login' first, or paste a PAT with repo + workflow scopes."
  ask_secret GH_TOKEN "Paste a GitHub token (blank to skip):"
fi
if [[ -n "$GH_TOKEN" ]]; then
  write_env GH_TOKEN "$GH_TOKEN"
  write_env GITHUB_TOKEN "$GH_TOKEN"
else
  SKIPPED+=("GH_TOKEN / GITHUB_TOKEN — the agent can't read tickets or push without one")
fi

say "Now the review-only token."
warn "must be FINE-GRAINED, not classic — classic has no separate Issues/PR"
warn "scope, so it always bundles Contents access and can't do this."
open_url "https://github.com/settings/personal-access-tokens/new"
step "That URL lands directly on the fine-grained form. If your browser or"
step "muscle memory redirects you to 'Tokens (classic)', go back — it won't work here."
step "Resource owner: your account. Repository access: the repos the loop"
step "runs against (this one, plus any registered project)."
step "Repository permissions: Issues → Read and write, Pull requests →"
step "Read and write, Contents → No access. Generate token, then copy it."
ask_secret GH_REVIEW_TOKEN "Paste the review token (blank to skip):"
if [[ -n "$GH_REVIEW_TOKEN" ]]; then
  write_env GH_REVIEW_TOKEN "$GH_REVIEW_TOKEN"
else
  SKIPPED+=("GH_REVIEW_TOKEN — review tickets won't start without it (README: 'Without it a review will not start')")
fi

# ── Stage 3: wire the tokens into every place the loop actually runs from ──
stage "Persist credentials"
say "Credentials just went into $ENV_FILE. Wiring that into an interactive"
say "shell and into cron — cron sources neither .bashrc nor .zshrc, so it"
say "needs its own copy of these as crontab-level environment lines."
chmod 600 "$ENV_FILE" 2>/dev/null || true

_install_rc_env "$HOME/.bashrc"
_install_rc_env "$HOME/.zshrc"

if command -v crontab >/dev/null 2>&1; then
  any=0
  for pair in "CLAUDE_CODE_OAUTH_TOKEN:${CLAUDE_CODE_OAUTH_TOKEN:-}" \
              "GH_TOKEN:${GH_TOKEN:-}" "GITHUB_TOKEN:${GH_TOKEN:-}" \
              "GH_REVIEW_TOKEN:${GH_REVIEW_TOKEN:-}"; do
    name="${pair%%:*}"; value="${pair#*:}"
    if [[ -n "$value" ]]; then
      _crontab_upsert_var "$name" "$value"
      any=1
    fi
  done
  (( any )) && printf '  %s✓%s crontab: credential(s) set as environment lines.\n' "$GREEN" "$RESET"
else
  SKIPPED+=("crontab not found — the cron trigger won't see these credentials")
fi

# ── Stage 4: the container image every run happens in ─────────────────────
stage "Sandbox image"
say "The container the agent runs in, built once and reused every run."
if confirm "Build it now (npm run sandbox:build && npm run sandbox:verify)?"; then
  if (cd "$REPO_DIR" && npm run sandbox:build); then
    if (cd "$REPO_DIR" && npm run sandbox:verify); then
      note "verified: harness plugin present and enumerating skills."
    else
      SKIPPED+=("sandbox:verify failed — investigate, then re-run 'npm run sandbox:verify'")
    fi
  else
    SKIPPED+=("sandbox:build failed — investigate, then re-run 'npm run sandbox:build'")
  fi
else
  SKIPPED+=("docker image — run 'npm run sandbox:build && npm run sandbox:verify' before the first morning loop invocation")
fi

echo
say "The image is built by hand, so a merge that changes the Dockerfile or a"
say "skill it bakes in leaves it stale. A post-merge hook says so on the spot."
if confirm "Install the repo's git hooks (npm run hooks:install)?"; then
  if (cd "$REPO_DIR" && npm run hooks:install); then
    note "installed: a merge that outdates the image now says so."
  else
    SKIPPED+=("hooks:install failed — investigate, then re-run 'npm run hooks:install'")
  fi
else
  SKIPPED+=("git hooks — run 'npm run hooks:install' from $REPO_DIR to be warned when a merge outdates the sandbox image")
fi

# ── Stage 5: the schedule ───────────────────────────────────────────────────
stage "Triggers"
say "A cron schedule firing every 15 minutes, installed by the repo's own"
say "idempotent installer, safe to run again later."
if confirm "Run 'npm run triggers:install' now?"; then
  if (cd "$REPO_DIR" && npm run triggers:install); then
    note "installed."
  else
    SKIPPED+=("triggers:install failed — investigate, then re-run 'npm run triggers:install'")
  fi
else
  SKIPPED+=("triggers — run 'npm run triggers:install' from $REPO_DIR yourself")
fi

# ── Stage 6: titles for interactive sessions ──────────────────────────────
stage "Session titles"
say "A UserPromptSubmit hook in ~/.claude/settings.json titles a session"
say "'<mode>: <owner/repo>[#n]' when you invoke a mode skill (see MODES in"
say "src/session-title.ts), in the /resume picker and the terminal tab."
say "It merges beside any hooks you already have and is safe to re-run."
if confirm "Install the session-title hook?"; then
  if (cd "$REPO_DIR" && node scripts/install-session-title-hook.ts); then
    note "installed into ~/.claude/settings.json."
  else
    SKIPPED+=("session-title hook — investigate, then run 'node scripts/install-session-title-hook.ts' from $REPO_DIR")
  fi
else
  SKIPPED+=("session-title hook — run 'node scripts/install-session-title-hook.ts' from $REPO_DIR to title interactive sessions")
fi

# ── Stage 7: optional — get one project onto the registry ─────────────────
stage "Register your first project"
say "Optional. registry.json only lists this manager repo right now, so the"
say "loop has nothing to work on until at least one project is added. You"
say "can always do this later with 'npm run new-project'."
if confirm "Register a project now?"; then
  ask PROJECT_REPO "owner/repo for the project:"
  if confirm "Does '$PROJECT_REPO' predate the manager (an existing repo, not a new one)?"; then
    say "Handing off to 'npm run new-project -- $PROJECT_REPO \"\" --existing' — interactive from here."
    (cd "$REPO_DIR" && npm run new-project -- "$PROJECT_REPO" "" --existing) \
      || SKIPPED+=("project registration for $PROJECT_REPO didn't finish — re-run 'npm run new-project -- $PROJECT_REPO \"\" --existing'")
  else
    ask PROJECT_IDEA "One-line idea (seeds its first tickets):"
    say "Handing off to 'npm run new-project -- $PROJECT_REPO \"$PROJECT_IDEA\"' — interactive from here."
    (cd "$REPO_DIR" && npm run new-project -- "$PROJECT_REPO" "$PROJECT_IDEA") \
      || SKIPPED+=("project registration for $PROJECT_REPO didn't finish — re-run 'npm run new-project -- $PROJECT_REPO \"$PROJECT_IDEA\"'")
  fi
else
  note "skipped — run 'npm run new-project -- owner/repo \"idea\"' (or --existing) when ready."
fi

finish
